# Generated by Django 3.2.5 on 2021-08-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=70)),
                ('data', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
